from libs.YCP.pages import YCP_base
from libs.YCP.pages import launcher
from libs.YCP.pages import photo_edit
from libs.YCP.pages import settings
from libs.YCP.pages import premium
from libs.YCP.pages import camera
from libs.YCP.pages import collage
from libs.YCP.pages import discovery
from libs.YCP.pages import store
from libs.YCP.pages import photo_picker
from libs.YCP.pages import how_to
from libs.YCP.pages import community_trending
from libs.YCP.pages import photo_challenge
from libs.YCP.pages import single_photo
from libs.YCP.pages import share
from libs.YCP.pages import result
from libs.YCP.pages import bc
