from libs.YMK.pages import YMK_base
from libs.YMK.pages import launcher_page
from libs.YMK.pages import photopicker_page
from libs.YMK.pages import photomakeup_page
from libs.YMK.pages import bodytuner_page
from libs.YMK.pages import removal_page
from libs.YMK.pages import animation_page
from libs.YMK.pages import effects_page
from libs.YMK.pages import background_page
from libs.YMK.pages import accessories_page
from libs.YMK.pages import makeupcam_page
from libs.YMK.pages import aging_page
from libs.YMK.pages import store_page
from libs.YMK.pages import result_page
from libs.YMK.pages import setting_page
from libs.YMK.pages import me_page
from libs.YMK.pages import bc_page
from libs.YMK.pages import skincare_page
from libs.YMK.pages import launcher_page
from libs.YMK.pages import smashbox_page
from libs.YMK.pages import cloud_album_view_page

